apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.grafanaservice }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.grafanaApplicationName}}
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  type: ClusterIP
