apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.serviceingress }}
  namespace: {{ .Values.namespace }}
  labels:
    name: {{ .Values.serviceingress }}
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.grafanaappbaseURL }}
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: {{ .Values.grafanaservice }}
            port:
              number: 3000
